{% set name = "jit-open" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jit_open-{{ version }}.tar.gz
  sha256: 288a220c3c7a1adaca8bb198dbb5b71e15544e792f93f0ade4df7ddda8dc69b7
  patches:
    - 001-entry-fixes.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - jit_open
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jfjlaros/jit-open
  summary: Just in time open files
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - acaprez
